srq_user_homepage:
    path:     /
    defaults: { _controller: SRQUserBundle:Default:index }
    
srq_user_index:
    path:     /index
    defaults: { _controller: SRQUserBundle:User:index }


srq_user_add:
    path:     /add
    defaults: { _controller: SRQUserBundle:User:add }



srq_user_create:
    path:     /create
    defaults: { _controller: SRQUserBundle:User:create }
    methods: POST

    
    
srq_user_edit:
    path:     /edit/{id}
    defaults: { _controller: SRQUserBundle:User:edit }
    
srq_user_update:
    path:     /update/{id}
    defaults: { _controller: SRQUserBundle:User:update }
    methods: [POST, PUT]
    
srq_user_view:
    path:     /view/{id}
    defaults: { _controller: SRQUserBundle:User:view }
    
srq_user_delete:
    path:     /delete/{id}
    defaults: { _controller: SRQUserBundle:User:delete }
    methods: [POST, DELETE]

srq_user_redirect_edit:
    path:     /update/{id}
    defaults:
        _controller: SRQUserBundle:User:edit
        path: /edit/{id}
        permanent: true