srq_user_user:
    resource: "@SRQUserBundle/Resources/config/routes/user.yml"
    prefix:   /user

srq_task_task:
    resource: "@SRQUserBundle/Resources/config/routes/task.yml"
    prefix:   /task

srq_dealer_dealer:
    resource: "@SRQUserBundle/Resources/config/routes/dealer.yml"
    prefix:   /dealer
    
    